### ISSUE TITLE
Not Authorized - Invalid Token

### ISSUE THREAD

**Issue by Invisiblearound** [Imperial-lord/mapbox-flutter#9]
Facing Issue : Not Authorized - Invalid Token

`Syncing files to device iPhone 13...
flutter: https://api.mapbox.com/geocoding/v5/mapbox.places/78.1198,9.9252.json?access_token=%3Cpk.eyJ1IjoiaW52aXNpYmxlIiwiYSI6ImNsMnJ4ZWswdjAwajQzZHFsNXJqYnpoYnUifQ.b9Cja-IhYcszZxUCEw1ZsQ%3E
flutter: Oops something went wrong
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
#0      getParsedReverseGeocoding (package:t..helpers/mapbox_handler.dart:42:19)
<asynchronous suspension>
#1      _SplashState.initializeLocationAndSave (package:../screens/authentication/splash.dart:48:10)
<asynchronous suspension>`

**Comment by Imperial-lord** [comment]
Did you add your SECRET key to .netrc file as instructed?

**Comment by JoelJoos** [comment]
I had this problem as well, have you tried adding your access token to the files as shown in the readme?
